
ALTER TABLE public.patients
  ADD COLUMN IF NOT EXISTS id_prontuario text,
  ADD COLUMN IF NOT EXISTS responsavel text,
  ADD COLUMN IF NOT EXISTS estado_civil text,
  ADD COLUMN IF NOT EXISTS profissao text,
  ADD COLUMN IF NOT EXISTS cep text,
  ADD COLUMN IF NOT EXISTS rua text,
  ADD COLUMN IF NOT EXISTS numero_endereco text,
  ADD COLUMN IF NOT EXISTS complemento text,
  ADD COLUMN IF NOT EXISTS bairro text,
  ADD COLUMN IF NOT EXISTS estado text,
  ADD COLUMN IF NOT EXISTS cidade text,
  ADD COLUMN IF NOT EXISTS pais text DEFAULT 'Brasil',
  ADD COLUMN IF NOT EXISTS telefone2 text,
  ADD COLUMN IF NOT EXISTS telefone3 text,
  ADD COLUMN IF NOT EXISTS convenio_padrao text,
  ADD COLUMN IF NOT EXISTS plano_saude text,
  ADD COLUMN IF NOT EXISTS numero_carteirinha text,
  ADD COLUMN IF NOT EXISTS data_nascimento date,
  ADD COLUMN IF NOT EXISTS sexo text,
  ADD COLUMN IF NOT EXISTS data_nascimento_responsavel date,
  ADD COLUMN IF NOT EXISTS carga_horaria_horas integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS carga_horaria_minutos integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cids_permanentes text,
  ADD COLUMN IF NOT EXISTS observacoes text,
  ADD COLUMN IF NOT EXISTS avatar_url text;
